/**
 * @ngdoc overview
 * @name hackstack demo app
 *
 * @description
 * Generated by Yo men
 *
 * **Note:** Describe what this module does
 *
 * @example
  http://localhost:8000
 */

angular.module('hackstack demo app', [ 'ngMaterial',
  'ngRoute',
  'hackstack'
])
.config([ '$routeProvider', '$locationProvider', function($routeProvider,$locationProvider) {

    $routeProvider
      .when('/', {
        templateUrl: 'routes/main/main.html',
        controller: 'main'
      })
      .otherwise({
        redirectTo: '/'
      });

    $locationProvider.html5Mode(true);

}])
/**
 * @ngdoc overview
 * @name $rootScope
 *
 * @description
 * Global Utility functions attached on the $rootScope of the ngdocs module
 **/
.run([ '$rootScope', '$location', 'hackstack', function($rootScope,$location, hackstack) {
  /**
   *
   * @ngdoc function
   * @name $rootScope.isActive
   *
   * @description
   * Global utility function,
   * used to apply active classes to link buttons
   *
   * @example
   <pre>
     <a href="/example" ng-class="{ 'active': isActive('/example') }">
       Example
     </a>
   </pre>
   */
  $rootScope.isActive = function (href) {
    return href === $location.path();
  };
    var mockData = [{"id": 0, "name": "Josefina"}, {"id": 1, "name": "Tereasa"}, {"id": 2, "name": "Simon"}, {"id": 3, "name": "Harry"}, {"id": 4, "name": "Vi"}, {"id": 5, "name": "Jule"}, {"id": 6, "name": "Brice"}, {"id": 7, "name": "Hiedi"}, {"id": 8, "name": "Val"}, {"id": 9, "name": "Kylee"}];

    window.mockAPI = hackstack.mock(mockData);
    hackstack.utils.disableRandomErrors(true);

    window.wrappedAPI = hackstack.wrap('//localhost:5000/cards/', {'desc': 'Description'}, {'priorityMock': true})
}]);

